2020-12-03 19:19:13,345 - teradata.udaexec - INFO - Initializing UdaExec...
2020-12-03 19:19:13,345 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\ag16000\\udaexec.ini: Not Found', 'C:\\Users\\ag16000\\OneDrive - Anthem\\Desktop\\GITHUB\\DS_ALGO\\udaexec.ini: Not Found']
2020-12-03 19:19:13,345 - teradata.udaexec - INFO - No previous run number found as C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO\.runNumber does not exist. Initializing run number to 1
2020-12-03 19:19:13,345 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2020-12-03 19:19:13,345 - teradata.udaexec - INFO - Removed 0 log files.
2020-12-03 19:19:13,353 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO\test.checkpoint
2020-12-03 19:19:13,353 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2020-12-03 19:19:13,353 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: test
 *          Version: 1.0
 *       Run Number: 20201203191913-1
 *             Host: LDMG1XT2
 *         Platform: Windows-10-10.0.18362-SP0
 *          OS User: AG16000
 *   Python Version: 3.7.6
 *  Python Compiler: MSC v.1916 64 bit (AMD64)
 *     Python Build: ('tags/v3.7.6:43364a7ae0', 'Dec 19 2019 00:42:30')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: C:/Users/ag16000/OneDrive - Anthem/Desktop/GITHUB/DS_ALGO/teradata_con_usi.py
 *      Working Dir: C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO
 *          Log Dir: C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO\logs
 *         Log File: C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO\logs\test.20201203191913-1.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\ag16000\\udaexec.ini: Not Found', 'C:\\Users\\ag16000\\OneDrive - Anthem\\Desktop\\GITHUB\\DS_ALGO\\udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=test;Version=1.0;JobID=20201203191913-1;ClientUser=AG16000;Production=False;udaAppLogFile=C:\Users\ag16000\OneDrive - Anthem\Desktop\GITHUB\DS_ALGO\logs\test.20201203191913-1.log;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2020-12-03 19:19:13,353 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'system': 'DWDEVCOP1.CORP.ANTHEM.COM', 'username': 'ag16000', 'password': 'XXXXXX', 'driver': 'DRIVERNAME'}
2020-12-03 19:19:13,360 - teradata.tdodbc - INFO - Available drivers: SQL Server, Teradata Database ODBC Driver 16.20
2020-12-03 19:19:13,360 - teradata.udaexec - ERROR - Unable to create connection: {'method': 'odbc', 'system': 'DWDEVCOP1.CORP.ANTHEM.COM', 'username': 'ag16000', 'password': 'XXXXXX', 'driver': 'DRIVERNAME'}
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\teradata\udaexec.py", line 183, in connect
    **args))
  File "C:\Python\lib\site-packages\teradata\tdodbc.py", line 427, in __init__
    connectParams["DRIVER"] = determineDriver(dbType, driver)
  File "C:\Python\lib\site-packages\teradata\tdodbc.py", line 381, in determineDriver
    " Available drivers: {}".format(driver, ",".join(drivers)))
teradata.api.InterfaceError: ('DRIVER_NOT_FOUND', "No driver found with name 'DRIVERNAME'.  Available drivers: SQL Server,Teradata Database ODBC Driver 16.20")
2020-12-03 19:19:13,362 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "C:/Users/ag16000/OneDrive - Anthem/Desktop/GITHUB/DS_ALGO/teradata_con_usi.py", line 10, in <module>
    password=password, driver="DRIVERNAME") as connect:
  File "C:\Python\lib\site-packages\teradata\udaexec.py", line 183, in connect
    **args))
  File "C:\Python\lib\site-packages\teradata\tdodbc.py", line 427, in __init__
    connectParams["DRIVER"] = determineDriver(dbType, driver)
  File "C:\Python\lib\site-packages\teradata\tdodbc.py", line 381, in determineDriver
    " Available drivers: {}".format(driver, ",".join(drivers)))
teradata.api.InterfaceError: ('DRIVER_NOT_FOUND', "No driver found with name 'DRIVERNAME'.  Available drivers: SQL Server,Teradata Database ODBC Driver 16.20")
2020-12-03 19:19:13,365 - teradata.udaexec - INFO - UdaExec exiting.
